---
name: Create new pull request
on:
  workflow_dispatch:
    inputs:
      head_branch:
        description: 'The head branch name'
        required: true
        type: string
        default: 'test-branch'

      base_branch:
        description: 'The base branch name'
        required: true
        type: string
        default: 'test-branch'
        
      title:
        description: 'The title of the PR'
        required: true
        type: string
        default: 'Test title'

      description:
        description: 'Description of PR'
        required: true
        type: string
        default: 'test description'

jobs:
  testing123:
    name: Test stuff
    runs-on: ubuntu-latest
    steps:    
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Create PR
        shell: bash
        env: 
          PR_HEAD_BRANCH: ${{ inputs.head_branch }}
          PR_BASE_BRANCH: ${{ inputs.base_branch }}
          PR_TITLE: ${{ inputs.title }}
          PR_DESCRIPTION: ${{ inputs.description }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base "$PR_BASE_BRANCH" --head "$PR_HEAD_BRANCH" --title "$PR_TITLE" --body "$PR_DESCRIPTION" 
