---
name: Publish to npm (if applicable)
on:
  pull_request:
    types: [opened]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, '[ Type ] NPM version update' )
    steps:
      - uses: Automattic/vip-actions/npm-publish@update/branch-protection-compatibility
        with:
          GH_TOKEN: ${{ secrets.GH_TESTS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
