---
name: test stuff
on:
  workflow_dispatch:
    inputs:
      # This is copied from npm-publish/action.yml
      npm-version-type:
        description: 'The npm version type we are publishing.'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  testing123:
    name: Test stuff
    runs-on: ubuntu-latest
    steps:    
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Checkout test
        run: git checkout -b test2

      - name: Step 1
        run: gh pr create --base trunk --head test2 --title "New release" --body "## Description \n\n<p>This pull request updates the npm package version number and should be auto-merged.</p>" --label '[ Type ] NPM version update' -a @me
        env:
           GH_TOKEN: ${{ secrets.GH_TESTS_TOKEN }}
