---
name: test stuff
on:
  workflow_dispatch:
    inputs:
      # This is copied from npm-publish/action.yml
      npm-version-type:
        description: 'The npm version type we are publishing.'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  testing123:
    name: Test stuff
    runs-on: ubuntu-latest
    steps:         
      - name: Step 1
        run: gh issue list
